server:
  port: 8761 # Eureka Server 공식 포트

spring:
  application:
    name: discovery-service # 서비스 ID (나중에 중요하게 쓰임)

eureka:
  client:
    register-with-eureka: false # 자기 자신을 등록할 필요 없음 (서버이므로)
    fetch-registry: false       # 다른 서버 목록을 가져올 필요 없음 (서버이므로)
  server:
    wait-time-in-ms-when-sync-empty: 0 # 서버 시작 시 대기 시간 없이 즉시 구동 (개발용 설정)