server:
  port: 7000

spring:
  cloud:
    gateway:
      routes:
        # 1. 인증 서버 (로그인은 누구나 가능해야 하므로 필터 X)
        - id: service-auth
          uri: lb://SERVICE-AUTH
          predicates:
            - Path=/auth/**

        # 2. 회원 서비스 (로그인 체크 필요!)
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter # [적용] 위에서 만든 클래스 이름

        # 3. 주문 서비스 (로그인 체크 필요!)
        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/orders/**
          filters:
            - AuthorizationHeaderFilter
            -
  application:
    name: service-auth

  # 1. 데이터베이스 연결 (로그인 시 비밀번호 확인용)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.25:6000/db_user  # 스키마 주의: db_user
    username: postgres
    password: Steveve14#

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 단계에서는 update, 운영 시 validate/none
    show-sql: true      # 쿼리 로그 보기
    properties:
      hibernate:
        format_sql: true

  # 3. Redis 연결 (Refresh Token 저장용)
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/

# 4. JWT 시크릿 키 설정 (임의로 지정)
token:
  secret: "c2lsdmVyLTI1Ni1iaXQtc2VjcmV0LWtleS1mb3ItjwtlbmNvZGluZy1leGFtcGxlCg==" # Base64 인코딩된 긴 문자열 권장
  expiration_time: 3600000       # Access Token 만료 시간 (1시간)
  refresh_time: 1209600000       # Refresh Token 만료 시간 (2주)