server:
  port: 8100  # 변경한 포트

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # 서버 자신이므로 등록하지 않음
    fetch-registry: false        # 서버 자신이므로 목록을 가져오지 않음
    service-url:
      # [중요] 여기를 8100으로 맞춰야 "8761 연결 실패" 에러가 사라집니다.
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/